    name: Building JavaScript
    run: |
      # Set up Emscripten environment
      source /opt/emsdk/emsdk_env.sh
      
      # Navigate to the directory containing the source code
      cd ./test/text
      
      # Compile the source code to WebAssembly
      emcc your_source_file.cpp -o output.js -s WASM=1
      
      # Check if the build was successful
      if [ $? -eq 0 ]; then
        echo "Build succeeded!"
      else
        echo "Build failed!"
        exit 1
      fi
      
      # Move the output files to the designated output directory
      mv output.js ../out/
      mv output.wasm ../out/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./test
          submodules: true
          
      - name: Set up Python for testing
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests -p "*.py"
          
      - name: Run JavaScript Tests
        run: |
          npm install
          npm test

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./test/text
          submodules: true
          
      - name: Build Documentation
        run: |
          cd ./docs
          make html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_branch: gh-pages
          
      - name: Notify Deployment Success
        run: echo "Deployment to GitHub Pages completed successfully!"
